import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:firebase_auth/firebase_auth.dart'; // Import Firebase Auth

// Import Screens
import 'screens/splash_screen.dart';
import 'screens/login_screen.dart';
import 'screens/home_screen.dart';
import 'screens/register_screen.dart'; // Import Register Screen
import 'screens/call_page.dart'; // Import Call Page

// Import Providers and Utils
import 'providers/user_provider.dart';
import 'providers/call_provider.dart'; // Import CallProvider for WebRTC
import 'utils/logger.dart';

// Import Firebase options (assuming firebase_options.dart is generated by FlutterFire CLI)
// If not using CLI, configure manually or ensure google-services.json/plist are correct.
// import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Logger.info('App Initialization Started.');

  // Initialize Firebase
  try {
    await Firebase.initializeApp(
      // Uncomment the line below if using firebase_options.dart
      // options: DefaultFirebaseOptions.currentPlatform,
    );
    Logger.info('Firebase Initialized Successfully.');
  } catch (e, stackTrace) {
    Logger.error('Firebase Initialization Failed', error: e, stackTrace: stackTrace);
    // Consider showing an error message to the user
  }

  // Force portrait orientation
  try {
    await SystemChrome.setPreferredOrientations([
      DeviceOrientation.portraitUp,
      DeviceOrientation.portraitDown,
    ]);
    Logger.info('Screen orientation set to portrait.');
  } catch (e, stackTrace) {
    Logger.error('Failed to set screen orientation', error: e, stackTrace: stackTrace);
  }

  Logger.info('Running LAMAFIA App.');
  runApp(const LAMAFIAApp());
}

class LAMAFIAApp extends StatelessWidget {
  const LAMAFIAApp({super.key});

  @override
  Widget build(BuildContext context) {
    Logger.debug('Building LAMAFIAApp Widget.');

    return MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (context) => UserProvider()),
        ChangeNotifierProvider(create: (context) => CallProvider()), // Add CallProvider
      ],
      child: MaterialApp(
        title: 'LAMAFIA', // App Title
        debugShowCheckedModeBanner: false, // Disable debug banner
        theme: _buildThemeData(), // Use the theme defined below

        // Use StreamBuilder to listen to Auth changes for routing
        home: StreamBuilder<User?>(
          stream: FirebaseAuth.instance.authStateChanges(),
          builder: (context, snapshot) {
            // Show splash screen while checking auth state
            if (snapshot.connectionState == ConnectionState.waiting) {
              return const SplashScreen(showIndicator: true); // Show indicator during check
            }
            // If user is logged in, go to Home
            if (snapshot.hasData && snapshot.data != null) {
              // Optionally fetch user data here or let UserProvider handle it
              // Provider.of<UserProvider>(context, listen: false).loadUserData(snapshot.data!.uid);
              return const HomeScreen();
            }
            // If user is not logged in, go to Login
            return const LoginScreen();
          },
        ),
        routes: {
          // Keep splash accessible if needed, but initial routing is handled by StreamBuilder
          '/splash': (context) => const SplashScreen(),
          '/login': (context) => const LoginScreen(),
          '/register': (context) => const RegisterScreen(), // Add Register route
          '/home': (context) => const HomeScreen(),
          '/call': (context) => const CallPage(), // Add CallPage route
        },
      ),
    );
  }

  ThemeData _buildThemeData() {
    return ThemeData(
      brightness: Brightness.dark,
      scaffoldBackgroundColor: const Color(0xFF1E1E2C), // Dark background
      primaryColor: const Color(0xFF9147FF), // Purple accent
      colorScheme: ColorScheme.dark(
        primary: const Color(0xFF9147FF), // Purple
        secondary: const Color(0xFF7289DA), // Discord-like blue/purple
        background: const Color(0xFF2C2F33), // Dark grey background elements
        surface: const Color(0xFF23272A), // Slightly lighter grey for surfaces
        onPrimary: Colors.white,
        onSecondary: Colors.white,
        onBackground: Colors.white70,
        onSurface: Colors.white,
        onError: Colors.redAccent,
      ),
      cardColor: const Color(0xFF2C2F33), // Card background
      appBarTheme: const AppBarTheme(
        backgroundColor: Color(0xFF23272A), // App bar background
        elevation: 0,
        foregroundColor: Colors.white, // Title/icon color
        titleTextStyle: TextStyle(
          color: Colors.white,
          fontSize: 20,
          fontWeight: FontWeight.bold,
          fontFamily: 'Gothic', // Ensure Gothic font is available
        ),
      ),
      inputDecorationTheme: const InputDecorationTheme(
        filled: true,
        fillColor: Color(0xFF23272A), // Input field background
        border: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(8)),
          borderSide: BorderSide.none,
        ),
        enabledBorder: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(8)),
          borderSide: BorderSide(color: Color(0xFF4F545C)), // Subtle border
        ),
        focusedBorder: OutlineInputBorder(
          borderRadius: BorderRadius.all(Radius.circular(8)),
          borderSide: BorderSide(color: Color(0xFF9147FF), width: 2), // Purple focus border
        ),
        labelStyle: TextStyle(color: Colors.white70, fontFamily: 'Gothic'),
        hintStyle: TextStyle(color: Colors.white54, fontFamily: 'Gothic'),
        prefixIconColor: Colors.white70,
        errorStyle: TextStyle(color: Colors.redAccent, fontFamily: 'Gothic'),
      ),
      textTheme: const TextTheme(
        bodyMedium: TextStyle(color: Colors.white70, fontFamily: 'Gothic', fontSize: 14),
        titleLarge: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontFamily: 'Gothic'),
        labelLarge: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontFamily: 'Gothic', fontSize: 16), // Button text
        headlineMedium: TextStyle(color: Colors.white, fontWeight: FontWeight.bold, fontFamily: 'Gothic'),
        titleMedium: TextStyle(color: Colors.white70, fontFamily: 'Gothic'),
        displayLarge: TextStyle(color: Colors.white, fontSize: 32, fontWeight: FontWeight.bold, fontFamily: 'Gothic'), // For Splash/Login Title
        displayMedium: TextStyle(color: Colors.white70, fontSize: 16, fontFamily: 'Gothic'), // For Splash/Login Subtitle
      ),
      iconTheme: const IconThemeData(color: Colors.white70),
      elevatedButtonTheme: ElevatedButtonThemeData(
        style: ElevatedButton.styleFrom(
          backgroundColor: const Color(0xFF9147FF),
          foregroundColor: Colors.white,
          padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 24),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
          textStyle: const TextStyle(fontSize: 16, fontWeight: FontWeight.bold, fontFamily: 'Gothic'),
        ),
      ),
      textButtonTheme: TextButtonThemeData(
        style: TextButton.styleFrom(
          foregroundColor: const Color(0xFF7289DA), // Secondary color for text buttons
          textStyle: const TextStyle(fontFamily: 'Gothic'),
        ),
      ),
      bottomNavigationBarTheme: const BottomNavigationBarThemeData(
        backgroundColor: Color(0xFF23272A),
        selectedItemColor: Color(0xFF9147FF),
        unselectedItemColor: Colors.white54,
        type: BottomNavigationBarType.fixed, // Ensure labels are always visible
        selectedLabelStyle: TextStyle(fontWeight: FontWeight.bold, fontSize: 12, fontFamily: 'Gothic'),
        unselectedLabelStyle: TextStyle(fontSize: 12, fontFamily: 'Gothic'),
      ),
      progressIndicatorTheme: const ProgressIndicatorThemeData(
        color: Color(0xFF9147FF), // Use primary color for indicators
      ),
    );
  }
}
